# Generated by Django 4.2.5 on 2023-09-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_alter_profile_bio_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.CharField(default='Hola mundo', max_length=200),
        ),
    ]
